services:
  - docker
language: 
  - python
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - docker build -t phelimb/mykrobe_predictor .
  - docker run phelimb/mykrobe_predictor nosetests
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests
git:
    submodules: false

